/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.java.aoc23;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class InputReaderTest {
    @Test
    void test_read_file_input() {
        String input = InputReader.read_file_input("1");
        System.out.println(input.charAt(0));
        assertEquals("t", input.substring(0, 1));
    }
}
